<?php $rows = array(
        0 =>
        array(
                'checkbox' => '',
                'title' => 'Elegant | High End Finishing | Affordable Luxury',
                'location' => 'Dubai - Mohammed Bin Rashid City - Sobha Hartland - Sobha Creek Vistas Grande',
                'size' => '1247',
                'bathrooms' => 3,
                'bedrooms' => 2,
                'type' => 'Apartment',
                'status' => 'Sale',
                'price' => '2,099,999.00',
                'category' => 'Residential',
                'time' => '2 hours ago',
                'button_class' => 'btn-success',
                'button_text' => 'Live',
                'image' => 'https://www.bhg.com/thmb/H9VV9JNnKl-H1faFXnPlQfNprYw=/1799x0/filters:no_upscale():strip_icc()/white-modern-house-curved-patio-archway-c0a4a3b3-aa51b24d14d0464ea15d36e05aa85ac9.jpg',
                'agency' => 'Think Realty-1336',
                'community' => 'test community',
                'agent' => 'test agent',
                'owner' => 'test owner',
        ),
        1 =>
        array(
                'checkbox' => '',
                'title' => 'Affordable Luxury | Prime Location | Top Amenities',
                'location' => 'Dubai - Mohammed Bin Rashid City - Sobha Hartland - Sobha Creek Vista Heights',
                'size' => '968',
                'bathrooms' => 2,
                'bedrooms' => 2,
                'type' => 'Apartment',
                'status' => 'Sale',
                'price' => '1,949,999.00',
                'category' => 'Residential',
                'time' => '3 hours ago',
                'button_class' => 'btn-warning',
                'button_text' => 'Pending',
                'image' => 'https://www.livehome3d.com/assets/img/articles/design-house/how-to-design-a-house.jpg',
                'agency' => 'Think Realty-1332',
                'community' => 'test community',
                'agent' => 'test agent',
                'owner' => 'test owner',
        ),

);
